Add blog post introducing the new inline execution containers feature
OctopusDeploy/blog pull request #1132
Opened 2024-04-30 07:01 UTC by hnrkndrssn

# About

This is a post about the new Inline Execution Containers feature that was introduced in `2024.1`.

[sc-63647]

# Blog image idea

I've reused the blog image from the original execution containers blog post.

# Before you submit your post

Check everything off this list before you submit your post for review. 

- [ ] I'm familiar with the [Octopus voice and style](https://www.octopus.design/932c0f1a9/p/13df3a-voice-and-style), the [guide for blog content basics](https://www.octopus.design/932c0f1a9/p/901d2a-blog-content), and [writing educational content](https://www.octopus.design/932c0f1a9/p/137b06-educational-content---how-we-write-about-what-we-do).
- [ ] I've checked the content using Grammarly (Octopus has a corporate license) and the [Hemingway app](https://hemingwayapp.com/) to remove typos, grammatical errors, and passive voice. 
- [ ] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://www.octopus.design/932c0f1a9/p/901d2a-blog-content/t/817249) and none of those apply.
- [ ] The images I've included follow the [rules for working with images](https://www.octopus.design/932c0f1a9/p/5061d7-working-with-images).
- [ ] I've added alt text for all the images I've included (alt text describes an image to people unable to see it, 125 characters max)
- [ ] The draft is complete and this post is ready to be reviewed. (Please mark the post 'ready for review' at the bottom of the PR.)
- [ ] I've dropped a note in Slack in #topic-content-marketing to let Tegan Ali know my post is ready for review. (No need to fill out a content brief.)
- [ ] I'll draft social media posts for Twitter and LinkedIn. I'll post them for review in #topic-social-media after the post has been edited or after the PR has been merged.

## How to review this PR

If there's anything you'd like reviewers to focus on, mention it here.

## Publication date

If there are considerations for when to publish this post, mention them here. For example, this post is supporting material for a webinar I'll be conducting on date, or this post should not published until after a specific release on date.

2024-05-01 04:33 UTC, IsaacCalligeros95 requested changes
A couple of small suggestions. I'm not 100% on the users/you terminology but I know we try and avoid saying customers. All my recommendations aren't around the actual content, which LGTM. Happy for my feedback to be ignored in favour the the changes from marketing.

2024-05-01 04:33 UTC, IsaacCalligeros95 commented on blog/2024-04/inline-execution-containers/index.md
> +description: Octopus 2024.1 added the ability to an inline Dockerfile or a URL to a Git repository to build the Docker container used for a deployment.
```suggestion
description: Octopus 2024.1 added the ability to use an inline Dockerfile or a URL to a Git repository to build the Docker container used for a deployment.
```

2024-05-01 04:33 UTC, IsaacCalligeros95 commented on blog/2024-04/inline-execution-containers/index.md
> +![Execution Containers for Workers](execution-workers.png)
I think this will already be shown by the bannerImage at the top level.

2024-05-01 04:33 UTC, IsaacCalligeros95 commented on blog/2024-04/inline-execution-containers/index.md
> +With the introduction of Execution Containers for steps we have simplified how users deploy applications using Octopus, providing a lightweight and portable solution for bundling dependencies needed
```suggestion
With the introduction of Execution Containers for steps we simplified how you deploy applications using Octopus, providing a lightweight and portable solution for bundling dependencies needed in your deployments into Docker containers.
```

2024-05-01 04:33 UTC, IsaacCalligeros95 commented on blog/2024-04/inline-execution-containers/index.md
> +We're excited to announce that we've improved this feature with a couple of new options that aims to simplify this process by offering users the flexibility to choose to use either an inline Dockerfi
```suggestion
We're excited to announce that we've improved this feature with a couple of new options that aim to simplify this process by offering users the flexibility to choose to use either an inline Dockerfile or a URL to a Git repository to build the Docker container image used for a deployment.
```

2024-05-01 04:33 UTC, IsaacCalligeros95 commented on blog/2024-04/inline-execution-containers/index.md
> +To create a Docker container image for use as an Execution Container involves writing a Dockerfile, which specifies the steps needed to build the container image with the necessary dependencies, and
```suggestion
Creating a Docker container image for use as an Execution Container involves writing a Dockerfile. This specifies the steps needed to build the container image with the necessary dependencies, and a CI/CD pipeline to publish the container image to a registry that Octopus can access (such as DockerHub or Azure Container Registry).
```

2024-05-01 04:33 UTC, IsaacCalligeros95 commented on blog/2024-04/inline-execution-containers/index.md
> +This approach offers greater flexibility and scalability, allowing users to leverage existing Dockerfiles maintained within their version control system.
```suggestion
This approach offers greater flexibility and scalability, allowing you to leverage existing Dockerfiles maintained within their version control system. 
```

2024-05-01 04:42 UTC, hnrkndrssn commented on blog/2024-04/inline-execution-containers/index.md
> +![Execution Containers for Workers](execution-workers.png)
Looks like that is true, it was a copy paste from the first blog post on execution containers so I've removed it now

2024-05-01 05:06 UTC, IsaacCalligeros95 approved these changes
LGTM

2024-05-02 04:54 UTC, TeganAli approved these changes

2024-05-02 05:06 UTC, merged