Kubernetes Worker
OctopusDeploy/blog pull request #1151
Opened 2024-08-20 06:34 UTC by rain-on

# About

This is a post about the introduction of the Kubernetes Worker.

# Release

This will be available in 2023.4.

# Blog image idea

Potentially the same one which is being used in the newsletter for this same topic.

# Before you submit your post

Check everything off this list before you submit your post for review. 

- [ ] I'm familiar with the [Octopus voice and style](https://www.octopus.design/932c0f1a9/p/13df3a-voice-and-style), the [guide for blog content basics](https://www.octopus.design/932c0f1a9/p/901d2a-blog-content), and [writing educational content](https://www.octopus.design/932c0f1a9/p/137b06-educational-content---how-we-write-about-what-we-do).
- [ ] I've checked the content using Grammarly (Octopus has a corporate license) and the [Hemingway app](https://hemingwayapp.com/) to remove typos, grammatical errors, and passive voice. 
- [ ] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://www.octopus.design/932c0f1a9/p/901d2a-blog-content/t/817249) and none of those apply.
- [ ] The images I've included follow the [rules for working with images](https://www.octopus.design/932c0f1a9/p/5061d7-working-with-images).
- [ ] I've added alt text for all the images I've included (alt text describes an image to people unable to see it, 125 characters max)
- [ ] The draft is complete and this post is ready to be reviewed. (Please mark the post 'ready for review' at the bottom of the PR.)
- [ ] I've dropped a note in Slack in #topic-content-marketing to let Tegan Ali know my post is ready for review. (No need to fill out a content brief.)
- [ ] I'll draft social media posts for Twitter and LinkedIn. I'll post them for review in #topic-social-media after the post has been edited or after the PR has been merged.

## How to review this PR

If there's anything you'd like reviewers to focus on, mention it here.

## Publication date

If there are considerations for when to publish this post, mention them here. For example, this post is supporting material for a webinar I'll be conducting on date, or this post should not published until after a specific release on date.

2024-08-21 02:44 UTC, NickJosevski requested changes
great! just a few small things

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +The Kubernetes Agent was our "man on the inside", simplifying deployments into a Kubernetes cluster.
```suggestion
The Kubernetes Agent was our "contact on the inside", simplifying deployments into a Kubernetes cluster. 
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +eventually applies pressure to the cluster - causing more hardware to be provisioned.
```suggestion
eventually applies pressure to the cluster - causing more capacity to be provisioned.
```

"causing more hardware to be provisioned" doesn't sound right, maybe more "capacity" to be provisioned?

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +The OctopusDeploy documentation suite covers the use of the Kubernetes Worker, otherwise reach out to our [community slack](https://octopususergroup.slack.com/archives/CBQ3FPQAH), or direct to our su
```suggestion
The Octopus Deploy documentation suite covers the use of the Kubernetes Worker, otherwise reach out to our [community slack](https://octopususergroup.slack.com/archives/CBQ3FPQAH), or direct to our support in case of trouble.
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +OctopusDeploy provides a number of ways for you to provide Worker compute resources:
```suggestion
Octopus Deploy provides a number of ways for you to provide Worker compute resources:
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +The Kubernetes Worker can be installed via the Kubernetes Agent [helm chart](https://hub.docker.com/r/octopusdeploy/kubernetes-agent) - you can do this manually via the command-line, but a far simple
```suggestion
The Kubernetes Worker can be installed via the Kubernetes Agent [helm chart](https://hub.docker.com/r/octopusdeploy/kubernetes-agent) - you can do this manually via the command-line, but a far simpler method is to use the “installation wizard” provided by the Octopus Deploy Web portal.
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +The Kubernetes worker is may not reduce complexity for the first groups.
```suggestion
The Kubernetes worker may not reduce complexity for the first groups. 
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +So if you're in group-3, you may find the Kubernetes Worker allows you to replace a fleet of workers machines, with a single Kubernetes Worker. One which will scale with your workloads.
```suggestion
So if you're in group-3, you may find the Kubernetes Worker allows you to replace a fleet of worker-machines, with a single Kubernetes Worker. One that will scale with your workloads.
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +The Kubernetes Worker uses the same polling communications protocol as Octopus Tentacle.It lets the worker connect from the cluster to Octopus Server (via proxy as required), solving potential networ
```suggestion
The Kubernetes Worker uses the same polling communications protocol as Octopus Tentacle. It lets the worker connect from the cluster to Octopus Server (via proxy as required), solving potential network access issues.
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +For the rest,  manual customization is available.
```suggestion
For the rest, manual customization is available.
```

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +Many aspects of the worker can be configured via its `Values`. Fopr now, these customisations must be performed via the command
```suggestion
Many aspects of the worker can be configured via its `values`. For now, these customisations must be performed via the command
```

non capitalised values is the correct one? earlier was non-caps.

2024-08-21 02:44 UTC, NickJosevski commented on blog/2024-08/kubernetes-worker/index.md
> +The full list of customisations are documented in the `Readme.md` of the [helm chart](https://hub.docker.com/r/octopusdeploy/kubernetes-agent).
```suggestion
The full list of customizations are documented in the `Readme.md` of the [helm chart](https://hub.docker.com/r/octopusdeploy/kubernetes-agent).
```
I thought something in the pipeline for docs and blogs, will force us spelling, so prepare for that maybe?

2024-08-21 03:22 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +eventually applies pressure to the cluster - causing more hardware to be provisioned.
changed "causing additional resources to be provisioned"

2024-08-21 03:25 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +The full list of customisations are documented in the `Readme.md` of the [helm chart](https://hub.docker.com/r/octopusdeploy/kubernetes-agent).
Definitely docs - maybe not blogs :/ Thanks for catching this one.

2024-08-21 03:27 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +Many aspects of the worker can be configured via its `Values`. Fopr now, these customisations must be performed via the command
I found a reference in the Kubernetes docs to 'Values', a kubernetes proper noun? For now, will go with capitalized V

2024-08-21 05:01 UTC, zentron approved these changes
Not going to block any merging, but just added some comments.
In general the second half of the How seems pretty good. Covers a bunch of ground. The first half though on the Why may need a few tweaks.

2024-08-21 05:01 UTC, zentron commented on blog/2024-08/kubernetes-worker/index.md
> +The installation wizard creates a Kubernetes worker which is appropriate for 90% of expected workloads.
was the `90%` figured based on something :) ?

2024-08-21 05:09 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +The installation wizard creates a Kubernetes worker which is appropriate for 90% of expected workloads.
magic - replaced with "majority"

2024-08-21 05:10 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +The words belong to go together; it took some work, but we've made it happen.
Shame! I love it :) But it doesn't add information to the blog so it can be removed.

2024-08-21 05:29 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +Whereas with a Kubernetes worker, each requested operation is executed in a new Kubernetes Pod (horizontal scaling), which
Rereading this, I didn't like the flow.
The sentence above talks about minimising idle time cost - while this paragraph talks about scaling.
I've rewritten it to merge together more cleanly (I think).

2024-08-21 06:58 UTC, NickJosevski approved these changes

2024-08-21 07:23 UTC, kevjt reviewed
good stuff

2024-08-21 07:23 UTC, kevjt commented on blog/2024-08/kubernetes-worker/index.md
> +4. At the end of the wizard, Octopus generates a Helm command that you copy and paste into a terminal connected to the target cluster. After it’s executed, Helm intsalls all the required resources an
```suggestion
4. At the end of the wizard, Octopus generates a Helm command that you copy and paste into a terminal connected to the target cluster. After it’s executed, Helm installs all the required resources and starts the agent.
```

2024-08-21 07:23 UTC, kevjt commented on blog/2024-08/kubernetes-worker/index.md
> +2. Change the image used by all Worker operations via the chart's `Values`.
Both these points can have links to more specific instructions

1. [link](https://octopus.com/docs/projects/steps/execution-containers-for-workers) to the execution containers for workers docs. 
2. [link](https://github.com/OctopusDeploy/docs/pull/2416/files#diff-6be41cbda3e4ea7cf27e51bb8636b5ba5e816a072f2261ee0c35087542fc0dd0R42) to doc section about customising the default worker image on script pods (once the k8 workers docs is actually released)

2024-08-21 07:23 UTC, kevjt commented on blog/2024-08/kubernetes-worker/index.md
> +If the worker-tools is not appropriate for your workloads, two options exist:
```suggestion
If the Worker-tools image is not appropriate for your workloads, two options exist:
```
Maybe capitalise to here indicate this is _the_ Octopus Worker-tools image?

2024-08-22 02:18 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +## How does the worker communicate?
```suggestion
## How the worker communicates
```

2024-08-22 02:20 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +2. You may be using the dynamic workers supplied by the Octopus Cloud platform if you're cloud-hosted.
```suggestion
2. Dynamic workers supplied by the Octopus Cloud platform if you're cloud-hosted.
```

2024-08-22 02:21 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +1. In the sidebar menu, navigate to **Deploy**, then **Workers** under **Infrastructure**, then **Add Worker**, then **Add Worker**, and then **Kubernetes Worker**.
@rain-on just checking, is this supposed to say "Add Worker" twice?

2024-08-22 02:22 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +4. At the end of the wizard, Octopus generates a Helm command that you copy and paste into a terminal connected to the target cluster. After it’s executed, Helm intsalls all the resources and starts
```suggestion
4. At the end of the wizard, Octopus generates a Helm command that you copy and paste into a terminal connected to the target cluster. After it’s executed, Helm installs all the resources and starts the agent.
```

2024-08-22 02:24 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +For the full list of customizations, you can refer to [helm chart README.md](https://hub.docker.com/r/octopusdeploy/kubernetes-agent).
```suggestion
For the full list of customizations, you can refer to the [Helm chart README.md](https://hub.docker.com/r/octopusdeploy/kubernetes-agent).
```

2024-08-22 03:11 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +The Kubernetes worker executes each deployment task in a new Kubernetes Pod (known as horizontal scaling). More resources are automatically provisioned when there's enough pressure on the cluster. Th
This sentence felt sort of off - is it worth rewording to something more like:

This reduces cost/effort in comparison to supporting a similar workload on physical/virtual worker machines.

2024-08-22 03:13 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +1. In the sidebar menu, navigate to **Deploy**, then **Workers** under **Infrastructure**, then **Add Worker**, then **Add Worker**, and then **Kubernetes Worker**.
that is definitely a mistake, duplication should be removed.

2024-08-22 03:14 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +You can configure many aspects of the worker via its values. For now, you need to perform these customizations via the command-line using a Helm upgrade command (or setting them manually during insta
Didn't like the word "via" being in there twice - but that might just be my itch :)
```suggestion
You can configure many aspects of the worker my modifying its Helm values. For now, you need to perform these customizations via the command-line using a Helm upgrade command (or setting them manually during install).
```

2024-08-22 03:15 UTC, rain-on commented on blog/2024-08/kubernetes-worker/index.md
> +For the full list of customizations, you can refer to the [Helm chart README.md](https://hub.docker.com/r/octopusdeploy/kubernetes-agent).
```suggestion
For the full list of customizations, you can refer to the [Helm chart README.md](https://github.com/OctopusDeploy/helm-charts/tree/main/charts/kubernetes-agent).
```

2024-08-22 03:20 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +The Kubernetes worker executes each deployment task in a new Kubernetes Pod (known as horizontal scaling). More resources are automatically provisioned when there's enough pressure on the cluster. Th
```suggestion
The Kubernetes worker executes each deployment task in a new Kubernetes Pod (known as horizontal scaling). More resources are automatically provisioned when there's enough pressure on the cluster. Then, as work gets completed and the pods terminate, the additional resources get returned to the cluster. This reduces the costand effort in comparison to supporting a similar workload on physical and virtual worker machines.
```

2024-08-22 03:21 UTC, TeganAli commented on blog/2024-08/kubernetes-worker/index.md
> +1. In the sidebar menu, navigate to **Deploy**, then **Workers** under **Infrastructure**, then **Add Worker**, then **Add Worker**, and then **Kubernetes Worker**.
```suggestion
1. In the sidebar menu, navigate to **Deploy**, then **Workers** under **Infrastructure**, then **Add Worker**, and then **Kubernetes Worker**.
```

2024-08-22 03:25 UTC, TeganAli approved these changes

2024-08-22 03:45 UTC, merged