Introduce Deployment freeze
OctopusDeploy/blog pull request #1190
Opened 2024-12-19 06:09 UTC by HuyPhanNguyen

# About
Deployment Freezes in Octopus Deploy. This feature enables organizations to restrict deployments during specific periods, ensuring system stability and compliance with business requirements. In this PR, we introduce the deployment freezes feature that allows teams to define and enforce deployment restrictions based on various time patterns (daily, weekly, monthly, and annual). The feature helps prevent unwanted deployments during critical business periods and maintains system reliability when it matters most.

# Release
2025.1

# Blog image idea

The design team will work on a design for the blog image. Add any ideas you have about the graphic image here. (Tegan will request the image from design and add it to the post when it's ready.)

# Before you submit your post

Check everything off this list before you submit your post for review. 

- [x] I'm familiar with the [Octopus voice and style](https://www.octopus.design/932c0f1a9/p/13df3a-voice-and-style), the [guide for blog content basics](https://www.octopus.design/932c0f1a9/p/901d2a-blog-content), and [writing educational content](https://www.octopus.design/932c0f1a9/p/137b06-educational-content---how-we-write-about-what-we-do).
- [x] I've checked the content using Grammarly (Octopus has a corporate license) and the [Hemingway app](https://hemingwayapp.com/) to remove typos, grammatical errors, and passive voice. 
- [x] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://www.octopus.design/932c0f1a9/p/901d2a-blog-content/t/817249) and none of those apply.
- [x] The images I've included follow the [rules for working with images](https://www.octopus.design/932c0f1a9/p/5061d7-working-with-images).
- [x] I've added alt text for all the images I've included (alt text describes an image to people unable to see it, 125 characters max)
- [x] The draft is complete and this post is ready to be reviewed. (Please mark the post 'ready for review' at the bottom of the PR.)
- [ ] I've dropped a note in Slack in #topic-content-marketing to let Tegan Ali know my post is ready for review. (No need to fill out a content brief.)
- [ ] I'll draft social media posts for Twitter and LinkedIn. I'll post them for review in #topic-social-media after the post has been edited or after the PR has been merged.

## How to review this PR

If there's anything you'd like reviewers to focus on, mention it here.

## Publication date

If there are considerations for when to publish this post, mention them here. For example, this post is supporting material for a webinar I'll be conducting on date, or this post should not published until after a specific release on date.

2024-12-19 06:50 UTC, benPearce1 commented on blog/2024-12/deployment-freeze/index.md
> +![Deployment Freeze Detail](deployment-freeze-detail.png)
All of the images need to have ` "width=500"` added after the filename. I think this keeps the images down to a reasonable size when rendered.

2024-12-19 06:55 UTC, benPearce1 commented on blog/2024-12/deployment-freeze/index.md
> +For regular maintenance windows or recurring business cycles, you can set up automated recurring freezes that align with your organization's needs.
Each line proceeding an image needs a blank line before the image or it ends up inlining the paragraph and image.

2024-12-19 07:10 UTC, benPearce1 commented on blog/2024-12/deployment-freeze/index.md
> +Deployment freezes in Octopus Deploy offer flexible scoping options for precise control over deployment restrictions. The scoping system provides two powerful options to give you granular control ove
```suggestion
Deployment freezes in Octopus Deploy offer flexible scoping options for precise control over deployment restrictions. The scoping configuration provides two powerful options to give you granular control over your deployment activities.
```

2024-12-20 02:23 UTC, hnrkndrssn submitted a review, later dismissed
Screenshots should be using the light mode, not dark.

2024-12-20 03:51 UTC, benPearce1 commented on blog/2024-12/deployment-freeze/index.md
> +- Match your maintenance windows
The problem with describing it as a maintenance window is that is the opposite of a freeze, for example, octopus cloud has a 2 hour maintenance window per day, that means that the freeze is the other 22 hours, per day.
A better example might be something like the end of month or end of financial year processing where they can't deploy during job runs.

2024-12-20 03:52 UTC, benPearce1 commented on blog/2024-12/deployment-freeze/index.md
> +- Monthly patterns for release cycles
This example is the same as I described above, where it feels like a release window rather than a release freeze.

2024-12-22 23:19 UTC, IsaacCalligeros95 reviewed
A couple of minor suggestions, in general looks good. It's a bit more conversational in style than I've written posts in the past but we do aim for a conversational style so I'll leave that to Tegan's judgement. Nice work!

2024-12-22 23:19 UTC, IsaacCalligeros95 commented on blog/2024-12/deployment-freeze/index.md
> +You get two main ways to control your freezes: project scope and tenant scope.
```suggestion
You can control your freezes by scoping them to projects or tenants.
```

2024-12-22 23:19 UTC, IsaacCalligeros95 commented on blog/2024-12/deployment-freeze/index.md
> +With project scope, you can freeze specific projects in certain environments. For example, you might want to freeze your online store deployments during Black Friday but keep working on your internal
```suggestion
With project scopes, you can freeze by environment. For example, you might want to freeze your online store production deployments during Black Friday but keep working on your development and test environments.
```

2024-12-22 23:19 UTC, IsaacCalligeros95 commented on blog/2024-12/deployment-freeze/index.md
> +Tenant scope lets you get even more specific. You can freeze deployments for particular tenants in selected projects and environments. This is super helpful if you're managing systems across differen
```suggestion
Tenant scope lets you get even more specific. You can freeze deployments for particular tenants in selected projects and environments. This is helpful if you're managing systems across different time zones or regions.
```

2024-12-22 23:19 UTC, IsaacCalligeros95 commented on blog/2024-12/deployment-freeze/index.md
> +You can automate and integrate deployment freezes into your workflows. Use the Octopus REST API and Terraform provider. For example, you can use the Go client to automate the creation and management
```suggestion
You can automate and integrate deployment freezes into your workflows using the Octopus REST API or the Terraform provider. For example, you can use the Go client to automate the creation and management of deployment freezes as part of your CI/CD pipeline. The Terraform provider offers an `octopusdeploy_deployment_freeze` resource for creating and managing deployment freezes. For more information, see the following resources:
```

2025-01-06 00:57 UTC, benPearce1 approved these changes

2025-01-15 02:37 UTC, michelle-luana commented on blog/2024-12/deployment-freeze/index.md
> +title: Introducing Deployment Freezes
I think we need a different title given that deployment freezes already exist with the product. Maybe something similar to below?
More control over Deployment Freezes: Recurring freezes and freeze by tenant

2025-01-15 03:03 UTC, michelle-luana requested changes

2025-01-15 03:03 UTC, michelle-luana commented on blog/2024-12/deployment-freeze/index.md
> +- Important demos or testing cycles when you need your systems stable
A couple of scenarios to add;

- You need to prevent deployments to production during business hours
- Your customers / branches are modelled with tenants and require more granular control around when deployments to those customers can proceed

2025-01-15 03:03 UTC, michelle-luana commented on blog/2024-12/deployment-freeze/index.md
> +Need to set up regular freezes for maintenance? No problem! You can set up automated recurring freezes that match your schedule.
Need to set up regular maintenance windows? No problem! You can set up automated recurring freezes that match your schedule.

2025-01-16 05:31 UTC, TeganAli commented
Hey @HuyPhanNguyen, let me know when you've addressed Michelle's feedback, been through the checklist at the top of the PR, and this is ready for my review. We're hoping to include this in the January newsletter, so it would be great if this was ready for my review before the end of the week 🙏

2025-01-20 21:51 UTC, michelle-luana approved these changes

2025-01-21 01:15 UTC, TeganAli approved these changes

2025-01-21 01:17 UTC, merged