Blog on Octopus and docker
OctopusDeploy/blog pull request #369
Opened 2020-11-16 16:57 UTC by AdminTurnedDevOps

# About

This is a post about creating a Docker instance on localhost for development purposes.

# Pre-requisites

- [x] The draft is complete and this post is ready to be reviewed.
- [x] I'm familiar with the [writing for Octopus TL;DR](https://style.octopus.com/writing-at-octopus-tldr).
- [x] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://style.octopus.com/writing-at-octopus-tldr#common-validation-errors) and none of those apply.
- [x] The images I've included follow the [rules for working with images](https://style.octopus.com/images#rules-for-screenshots).

2020-12-01 06:08 UTC, wordlee commented
Hi Michael, great post. A couple of requests, can you retake the login screen shot in light mode and with the login modal centered, and can you add the code to an Octopus repo. Thanks!

2020-12-01 06:09 UTC, wordlee requested changes
Hi Michael, great post. A couple of requests, can you retake the login screen shot in light mode and with the login modal centered, and can you add the code to an Octopus repo. Thanks!

2020-12-01 15:46 UTC, AdminTurnedDevOps commented
@wordlee 

Hey Lee,

Here is the code: https://github.com/OctopusSamples/OctopusDeploy-Local-Docker-Env

In terms of the screenshot - I can absolutely make it light mode, but the thing is, the container by default is created with dark mode. Because of that, what the user sees vs what is shown in the blog post won't be the same. Thoughts?

2020-12-02 01:17 UTC, wordlee commented
> @wordlee
> 
> Hey Lee,
> 
> Here is the code: https://github.com/OctopusSamples/OctopusDeploy-Local-Docker-Env
> 
> In terms of the screenshot - I can absolutely make it light mode, but the thing is, the container by default is created with dark mode. Because of that, what the user sees vs what is shown in the blog post won't be the same. Thoughts?

Interesting. Do you know if it creates it in dark mode in response to your system settings or by default? Personally, I prefer dark mode, but we decided to standardize on light mode.

2020-12-02 01:17 UTC, wordlee commented on blog/2020-11/set-up-octopus-deploy-on-docker-in-five-minutes/index.md
> +The code in this post is available in [GitHub](https://github.com/AdminTurnedDevOps/OctopusDeploy-Local-Docker-Env)
```suggestion
The code in this post is available in [GitHub](https://github.com/OctopusSamples/OctopusDeploy-Local-Docker-Env)
```

2020-12-02 05:15 UTC, robpearson reviewed
Hi Michael, this is great post. I really enjoyed reading it. Short and sweet and useful for our customers to get up and running w/ Octopus and Docker. Few suggestions on the high level clarity. :) 

I would suggest tweaking the title and description to match the post a bit better. Actually, I think your title is perfect. ;) I would tweak the description slightly. 

Learn how to configure Octopus Deploy to run on Docker on your local computer.

I'd tweak your headlines so they're more scalable. i.e. People can grok the broad context quickly.

Intro (no headline)
## Prerequisites
## Configure your environment
## Configure Docker Compose to run Octopus Containers
## Run the Docker Compose file

I think the references to localhost could be clearer. i.e. I would say something like your local computer or your local workstation instead of localhost. I'd suggest reviewing the usages and updating them.

I'd also add a link in the intro and conclusion to Matt's announcement post (https://octopus.com/blog/introducing-linux-docker-image) which goes into further detail on how to run this on Kubernetes etc. It's a good post for people who want to dig in deeper.

2020-12-02 18:33 UTC, AdminTurnedDevOps commented
> > @wordlee
> > Hey Lee,
> > Here is the code: https://github.com/OctopusSamples/OctopusDeploy-Local-Docker-Env
> > In terms of the screenshot - I can absolutely make it light mode, but the thing is, the container by default is created with dark mode. Because of that, what the user sees vs what is shown in the blog post won't be the same. Thoughts?
> 
> Interesting. Do you know if it creates it in dark mode in response to your system settings or by default? Personally, I prefer dark mode, but we decided to standardize on light mode.

@wordlee Hm, that's a good point. I'm going to change my settings on my Mac to light mode and give it a shot.

2020-12-02 18:44 UTC, AdminTurnedDevOps commented on blog/2020-11/set-up-octopus-deploy-on-docker-in-five-minutes/index.md
> +This containerized environment is supposed to be for testing/development purposes only, which is why you will see the passwords in the `.env` configuration file. This is not recommended for productio
@robpearson We should chat about this. The TLDR is; there are a few things that need to be done in the product itself before the containers can be considered "production-ready". Let's chat when you have some time about this.

2020-12-02 18:45 UTC, AdminTurnedDevOps commented on blog/2020-11/set-up-octopus-deploy-on-docker-in-five-minutes/index.md
> +The Docker Compose file creates a running container for the Octopus Deploy environment to run on localhost. The Compose file consists of two configurations:
Done :)

2020-12-14 04:54 UTC, merged