Docker and Kubernetes blog post
OctopusDeploy/blog pull request #377
Opened 2020-12-07 14:36 UTC by AdminTurnedDevOps

# About

This is a post about the news with the Docker runtime being deprecated on Kubernetes

# Pre-requisites

- [x] The draft is complete and this post is ready to be reviewed.
- [x] I'm familiar with the [writing for Octopus TL;DR](https://style.octopus.com/writing-at-octopus-tldr).
- [x] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://style.octopus.com/writing-at-octopus-tldr#common-validation-errors) and none of those apply.
- [x] The images I've included follow the [rules for working with images](https://style.octopus.com/images#rules-for-screenshots).

2020-12-08 02:08 UTC, robpearson reviewed
Great post. I added a few suggestions for SEO and scan-ability. You might need to reword them so they fit the context better. i.e. I'm not an K8s expert. :)

2020-12-08 02:08 UTC, robpearson commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +I promise you that this is not as crazy or insane as it sounds. In fact, this entire thing has been planned for years now. If you're a user of Kubernetes, for example, you're using Azure Kubernetes S
```suggestion
I promise you that this is not as crazy or insane as it sounds. In fact, this entire thing has been planned for years now. If you're a user of Kubernetes, for example, you're using Azure Kubernetes Service (AKS) or AWS Elastic Kubernetes Service (EKS), not a lot is changing for you. It's pretty much going to continue to be the same. For example, if you upgrade the Kubernetes API version in AKS to 1.19, then you're already running containerd (we'll get into containerd in a second), which is a runtime, like the Docker runtime.
```

2020-12-08 02:08 UTC, robpearson commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +## What's actually happening
I'd suggest sprinkling a few links through this section to help people who aren't super familiar with things. i.e. I didn't know what `CRI-0` was etc. A few helpful links would help me fill the gaps. :)

2020-12-08 02:08 UTC, robpearson commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +title: Docker and Kubernetes - what's happening?
I think we need a clearer title clarifying what is happening. Something like `Kubernetes 1.20 is deprecating Docker - What's happening?` or `What does it all mean?`

2020-12-08 02:08 UTC, robpearson commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +## What's actually happening
Tweak for scan-ability and SEO - `Kubernetes 1.20 is deprecating Docker - What's actually happening?`

2020-12-08 02:08 UTC, robpearson commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +## This was all planned
Tweak for scan-ability and SEO - `Kubernetes is deprecating Dockershim - This was planned`

2020-12-08 02:10 UTC, robpearson commented
One final thought.I wonder if it needs a conclusion. i.e. A one line summary of the entire story. ;)

2020-12-08 19:46 UTC, AdminTurnedDevOps commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +## This was all planned
Done!

2020-12-08 19:46 UTC, AdminTurnedDevOps commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +## What's actually happening
Done

2020-12-08 19:46 UTC, AdminTurnedDevOps commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +title: Docker and Kubernetes - what's happening?
Added :)

2020-12-08 19:51 UTC, AdminTurnedDevOps commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +## What's actually happening
Done

2020-12-08 19:53 UTC, AdminTurnedDevOps commented
@robpearson Hey Rob, just pushed up the updates :)

2020-12-09 05:48 UTC, wordlee commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Kubernetes maintaining Dockershim was becoming a huge weight on their shoulders. With that comes the CRI standard. The CRI standard was created to lift the weight of their shoulders. It allows for a
It's quite clear to me what is being said here. The third sentence feels like it contradicts the second sentence. Perhaps you could expand on "What that comes the CRI standard", or maybe that line could be deleted?

2020-12-09 05:49 UTC, wordlee requested changes
Changes requested in the PR

2020-12-09 13:56 UTC, AdminTurnedDevOps commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Kubernetes maintaining Dockershim was becoming a huge weight on their shoulders. With that comes the CRI standard. The CRI standard was created to lift the weight of their shoulders. It allows for a
@wordlee Hey Lee. I changed this around a bit. Let me know if it makes more sense.

2020-12-11 04:29 UTC, wordlee commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Kubernetes maintaining Dockershim was becoming a huge weight on their shoulders because Dockershim was an extra/added hop to get to the runtime in Kubernetes. Because of that, Kubernetes decided to g
```suggestion
Kubernetes maintaining Dockershim was becoming a huge weight on their shoulders because Dockershim was an extra hop to get to the runtime in Kubernetes. Because of that, Kubernetes decided to go towards using CRI, which allows for a very smooth transition for interoperability for container runtimes. That means, no more "hop" is needed.
```

2020-12-11 04:35 UTC, wordlee commented on blog/2020-12/docker-and-kubernetes-whats-happening/index.md
> +Containerd, much like [CRI-O](https://www.redhat.com/en/blog/introducing-cri-o-10#:~:text=CRI%2DO%3A%20A%20Lightweight%20Container%20Runtime%20for%20Kubernetes&text=The%20name%20derives%20from%20CRI,
```suggestion
Containerd, much like [CRI-O](https://www.redhat.com/en/blog/introducing-cri-o-10#:~:text=CRI%2DO%3A%20A%20Lightweight%20Container%20Runtime%20for%20Kubernetes&text=The%20name%20derives%20from%20CRI,support%20any%20OCI%2Dconformant%20runtime.), is a container runtime that is part of the Open Container Initiative ([OCI](https://opencontainers.org/)). 
```

2020-12-11 04:36 UTC, wordlee commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Containerd, much like [CRI-O](https://www.redhat.com/en/blog/introducing-cri-o-10#:~:text=CRI%2DO%3A%20A%20Lightweight%20Container%20Runtime%20for%20Kubernetes&text=The%20name%20derives%20from%20CRI,
```suggestion
Containerd, much like [CRI-O](https://www.redhat.com/en/blog/introducing-cri-o-10#:~:text=CRI%2DO%3A%20A%20Lightweight%20Container%20Runtime%20for%20Kubernetes&text=The%20name%20derives%20from%20CRI,support%20any%20OCI%2Dconformant%20runtime.), is a container runtime that is part of the Open Container Initiative ([OCI](https://opencontainers.org/)). 
```

2020-12-11 04:39 UTC, wordlee commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Docker in itself was a monolith and that's how it was built. Because they wanted to move into a modern application approach, various things were changed. The one component you're most likely interest
```suggestion
Docker in itself was a monolith and that's how it was built. Because they wanted to move into a modern application approach, various things were changed. The one component you're most likely interested is in, as you may think, the runtime. Instead, it's actually [Dockershim](https://godoc.org/k8s.io/kubernetes/pkg/kubelet/dockershim).
```

2020-12-11 04:50 UTC, wordlee commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Docker in itself was a monolith and that's how it was built. Because they wanted to move into a modern application approach, various things were changed. The one component you're most likely interest
This sentence needs some work. I sort of know what you're trying to say, "they" and "various things" should be more specific so there's no ambiguity.

The structure of this sentence is difficult to untangle:

The one component you're most likely interested in is, as you may think, the runtime. Instead, it's actually [Dockershim]

Would something like this work: The runtime is provided Dockershim, and this is the component that's causing all the confusion.

2020-12-11 04:56 UTC, wordlee commented on blog/2020-12/kubernetes-1-20-deprecating-docker-runtime/index.md
> +Kubernetes maintaining Dockershim was becoming a huge weight on their shoulders. With that comes the CRI standard. The CRI standard was created to lift the weight of their shoulders. It allows for a
Thanks @AdminTurnedDevOps. A couple of comments further down :)

2020-12-14 01:50 UTC, wordlee commented
I made the last few changes based on my best judgment as the post is publishing today.

2020-12-14 03:21 UTC, merged