Config as code strategies
OctopusDeploy/blog pull request #705
Opened 2022-02-24 09:20 UTC by steve-fenton-octopus

# About

This post explains the recommend usage of Config as Code.

# Release

This relates to the Config as Code switch from EAP to general availability and I believe the Config as Code team would like to time this post to coincide with the launch.

# Blog image idea

The design team will work on a design for the blog image. Add any ideas you have about the graphic image here.

# Pre-requisites

- [ ] The draft is complete and this post is ready to be reviewed.
- [ ] I'm familiar with the [writing for Octopus TL;DR](https://www.octopus.design/writing/writing-tldr/).
- [ ] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://style.octopus.com/writing-at-octopus-tldr#common-validation-errors) and none of those apply.
- [ ] The images I've included follow the [rules for working with images](https://www.octopus.design/writing/working-with-images/).
- [ ] I've added alt text for all the images I've included (alt text describes image to people unable to see it, 125 characters max)
- [ ] One screenshot (if any are included) is suitable for Twitter. This screenshot should be 16:9 ratio and at least 1200 x 675 pixels. For screenshots from the Octopus Web Portal, please use Chrome and the browser’s zoom function to remove as much white space as possible. If screenshots are annotated (e.g., with boxes or arrows), please also provide a version that is unannotated for use on Twitter. Do not use dark mode for the Octopus Web Portal.

## How to review this PR

## Publication date

Tied to the Config as Code launch.

2022-03-07 03:37 UTC, wordlee commented on blog/2022-03/config-as-code-strategies/index.md
> +Since last year, when we released the early-access preview of Octopus Config as Code, there have been many questions about how to use the feature to get the best results. This article will explain so
Slight tweak to the opening sentence:
```suggestion
Since we released the early-access preview of Octopus Config as Code last year, there have been many questions about how to use the feature for the best results. This article explains some good practices for using config as code and how to adjust your strategy in different situations.
```

2022-03-07 03:38 UTC, wordlee commented on blog/2022-03/config-as-code-strategies/index.md
> +The Octopus Config as Code feature enables you to store your deployment process as configuration files in a Git repository rather than in the Octopus database. You can use config as code to:
Enables always feels like a complicated word than is necessary :)
```suggestion
The Octopus Config as Code feature lets you store your deployment process as configuration files in a Git repository rather than in the Octopus database. You can use config as code to:
```

2022-03-07 03:42 UTC, wordlee commented on blog/2022-03/config-as-code-strategies/index.md
> +Each option is described below to explain when they work and when to avoid them. You might have noticed that you can arrange these possibilities along a scale from a one-to-one relationship with appl
```suggestion
Read on, to learn when each option works best and when to avoid them. You might have noticed that you can arrange these possibilities along a scale from a one-to-one relationship with applications to a single large repository. We recommend keeping your deployment configuration in the same repository as the application code, but there are specific circumstances where the other options may be suitable.
```

2022-03-07 03:44 UTC, wordlee commented on blog/2022-03/config-as-code-strategies/index.md
> +If you don't want changes to the deployment process to trigger a build, you can mask the `.octopus` folder in your build server.
It might not be necessary, but I wonder if it's worth expanding on this point a bit just to make it really clear what's been built?
```suggestion
If you don't want changes to the deployment process to trigger a build of your application, you can mask the `.octopus` folder in your build server.
```

2022-03-07 03:51 UTC, wordlee requested changes
Looks good, Steve. I've left a couple of small comments

2022-03-10 06:38 UTC, TeganAli commented
Hey @steve-fenton-octopus 
I finally got around to reviewing this, and wow, this is awesome. You're such a brilliant writer. This post was such a pleasure to read. I look forward to all the posts to come from you :)

2022-03-22 11:43 UTC, steve-fenton-octopus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Config as Code stategies](https://trello.com/c/I0pwdFoD/1-config-as-code-stategies)

2022-03-28 06:10 UTC, merged