Config as Code Slugs
OctopusDeploy/blog pull request #794
Opened 2022-06-24 03:42 UTC by YuKitsune

# About

This is a post about...

# Release

Is this post for a specific release? If so which one?

# Blog image idea

The design team will work on a design for the blog image. Add any ideas you have about the graphic image here.

# Pre-requisites

- [ ] The draft is complete and this post is ready to be reviewed.
- [ ] I'm familiar with the [writing for Octopus TL;DR](https://www.octopus.design/writing/writing-tldr/).
- [ ] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://style.octopus.com/writing-at-octopus-tldr#common-validation-errors) and none of those apply.
- [ ] The images I've included follow the [rules for working with images](https://www.octopus.design/writing/working-with-images/).
- [ ] I've added alt text for all the images I've included (alt text describes image to people unable to see it, 125 characters max)
- [ ] One screenshot (if any are included) is suitable for Twitter. This screenshot should be 16:9 ratio and at least 1200 x 675 pixels. For screenshots from the Octopus Web Portal, please use Chrome and the browser’s zoom function to remove as much white space as possible. If screenshots are annotated (e.g., with boxes or arrows), please also provide a version that is unannotated for use on Twitter. Do not use dark mode for the Octopus Web Portal.

## How to review this PR

## Publication date

2022-07-11 00:40 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +Now that we had decided to use names in OCL, we had to figure out how we were going to convert IDs to names when writing OCL. We could've easily written a converter that explicitly replaces all IDs w
There is a mix of tenses here.
Change
> ~Now~ that we had decided

to

> Once we had decided

2022-07-11 00:57 UTC, zentron requested changes
Its a nice start thanks @YuKitsune . I'd like to see it talk more about the reasoning behind our decisions, the pros and cons that led us to the final decision and the final impacts of that behavior at a higher level.

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +This could've worked, but it wouldn't scale very well.
Feel like we should keep the TinyTypes discussion out of this to simplify the focus to being just about the names/Ids/Slugs decisions.

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +The decision to use names in OCL was made before [document stores](https://octopus.com/blog/config-as-code-persistence-ignorance) were implemented into the Octopus codebase. We also lacked a solid ca
I could be wrong but I think the decision to just use names once converted was more just about the ability to get better feedback on an OCL document with a name that doesnt exist. As called out in the [original presentation](https://docs.google.com/presentation/d/168KWp7NyvAGBvHv8JeSqczRsY5mRHcM6agZu_98kLJw/edit#slide=id.g1047ab0d1e3_0_12) the change back to slugs to break this was considered worth the cost.

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +Because our API doesn't support lookups by name, consumers would need to use our generic list-style endpoints (E.g: `/projects`) to find all resources and manually search through their names.
Its worth really drilling home the fact that once you get a resource from octopus, but _using_ names the **consumer looses all knowledge about what a specific identity relates to**. It could be a name OR Id, and as a result the user (and our own code) would often need to try guess which type it was (and potentially get it wrong). This violates one of our goals of an identity, that it is _uniquely identifiable._

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +With all of the grief caused by names as IDs, a number of teams within R&D sought out alternatives.
Nitpick. It wasn't a number of teams within R&D... it was CaC ;)

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +## Fully-qualified slugs
I'd consider leaving this out for now, or perhaps keeping as a side comment. We dont technically expose fully qualified slugs anywhere at the moment so could just confuse.

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +When we began working on slugs, we chose to add slugs to a handful of resources, with plans to add slugs to remaining documents later on, keeping the initial scope narrow, and allowing for room to gr
Maybe a little more clarity on why we chose a handful? 
Mention specifically we are currently only adding slugs to entities which need to be referenced in OCL since that is there main purposes at the moment. Their usage may expand later.

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +### Introducing Slug Providers
Again, I'd probably just opt to keep this as non-technical as possible to really focus on the decisions around Ids/names/slugs and what slugs are for. To some extend the specifics of the classes used aren't overly important to the user, what is important is the new rules and behaviors.

Maybe just keep this section on point talking about the fact that we isolate the abstraction leak of slugs to the OCL layer, such that during deserialisation we convert them to Ids to allow all our internal and API code to continue thinking in terms of Ids. Why do we do that?

2022-07-11 00:57 UTC, zentron commented on blog/2022-q3/what-are-slugs-and-why-did-we-choose-them/index.md
> +```cs
Again, i'd remove code here even if we keep some of the q/a like the above.

2022-07-12 05:30 UTC, YuKitsune commented
Thanks @zentron 
I _think_ I've addressed most of your feedback. Let me know what you think.

2022-07-19 06:35 UTC, zentron approved these changes
Content-wise I like this one now. It tells a good story of the journey to where we ended up.
Nice work @YuKitsune

2022-07-20 02:23 UTC, TeganAli approved these changes

2022-07-20 02:28 UTC, merged