Uploaded 'Microservices and frameworks' blog post
OctopusDeploy/blog pull request #796
Opened 2022-07-01 07:48 UTC by AndyCorrigan

# About

This is a post about...

# Release

Is this post for a specific release? If so which one?

# Blog image idea

The design team will work on a design for the blog image. Add any ideas you have about the graphic image here.

# Pre-requisites

- [ ] The draft is complete and this post is ready to be reviewed.
- [ ] I'm familiar with the [writing for Octopus TL;DR](https://www.octopus.design/writing/writing-tldr/).
- [ ] The PR build passes validation, and if it doesn't, I've checked the [common validations errors](https://style.octopus.com/writing-at-octopus-tldr#common-validation-errors) and none of those apply.
- [ ] The images I've included follow the [rules for working with images](https://www.octopus.design/writing/working-with-images/).
- [ ] I've added alt text for all the images I've included (alt text describes image to people unable to see it, 125 characters max)
- [ ] One screenshot (if any are included) is suitable for Twitter. This screenshot should be 16:9 ratio and at least 1200 x 675 pixels. For screenshots from the Octopus Web Portal, please use Chrome and the browser’s zoom function to remove as much white space as possible. If screenshots are annotated (e.g., with boxes or arrows), please also provide a version that is unannotated for use on Twitter. Do not use dark mode for the Octopus Web Portal.

## How to review this PR

## Publication date

2022-07-04 22:13 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +Especially useful for web applications, software built this way sees each *feature* hosted in a separate container. Users then access the whole application and its features through a front end (also
Calling out web applications, features, and containers here may be too specific for a general introduction:

> Especially useful for web applications, software built this way sees each *feature* hosted in a separate container

I've found the ebook at https://raw.githubusercontent.com/dotnet-architecture/eBooks/main/current/microservices/NET-Microservices-Architecture-for-Containerized-NET-Applications.pdf to be quite useful, as it is based on a practical example and doesn't get too bogged down in theory. They have this as their description of microservices:

> As the name implies, a microservices architecture is an approach to building a server application as a set of small services.

Specifically, microservices have been used mostly for server applications (as opposed to web applications) from a set of small services (as opposed to features). And while containers are a natural fit for microservices, they are not a requirement.

2022-07-04 22:16 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +Especially useful for web applications, software built this way sees each *feature* hosted in a separate container. Users then access the whole application and its features through a front end (also
> Users then access the whole application and its features through a front end (also in its own container), unaware of the difference in delivery.

Again, calling out the fact that the frontend is in a container is too specific for this general introduction. Of all the components of a microservice stack, the frontend is actually the most likely to not be in a container. A lot of platforms exist to speed the delivery of static frontend resources, like content delivery networks (CDNs), and often CDNs are backed by simple file hosting rather than a container service.

So I would just drop the reference to containers in this sentence.

2022-07-04 22:21 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +Let's imagine you're building a retail website built in microservices. You might decide the following features should live in their own containers:
I suspect you may have associated the idea of a container with a microservice.

Containers provide a useful method for delivering microservices, but are not a requirement. Likewise, container orchestration platforms like Kubernetes provide useful features for hosting microservices, but again you are not required to use Kubernetes (or any other container platform) to use microservices.

So this sentence:

> You might decide the following features should live in their own containers:

Should read:

> You might decide the following features should live in their own microservices:

2022-07-04 22:26 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +- Website front-end (HTML, CSS etc)
This is a good list. It fits with nicely with how other teams have broken down their [example microservice stores](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/introduce-eshoponcontainers-reference-app#features-and-requirements).

2022-07-04 22:28 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +### Java
You have captured most of them here, but this list has a few other options you could add: https://www.infoworld.com/article/3664079/8-java-frameworks-for-a-cloud-native-world.html

2022-07-04 22:29 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +A microservices framework from Java-framework provider, Spring.
Spring boot is not necessarily a microservices framework. I would go with the sub project "Spring Cloud Functions" instead, which is focused on microservices.

2022-07-04 22:34 UTC, mcasperson commented on blog/2022-q3/microservices-and-frameworks/index.md
> +### .NET and C#
Some other options:

- https://github.com/dotnet/tye
- https://steeltoe.io/

2022-07-04 22:46 UTC, mcasperson requested changes
Overall the concepts presented here capture the general idea of microservices well. It is a light introduction that doesn't go into unnecessary detail.

Some of the content confuses containers with microservices, but it shouldn't take much to replace those occurrences.

The list of frameworks for .NET users was a little light. I suspect this reflects reality, where most of the energy building microservice frameworks has been directed at more "open" platforms, but there are a few notable projects from Microsoft that would be worth including.

2022-07-07 00:30 UTC, TeganAli approved these changes

2022-07-07 00:42 UTC, merged